// arrays - products
const profile_descriptions = [
  'ALU - Abdichtkappe',
  'ALU - Abschlussprofil',
  'ALU - Abschlussprofil Alupaneel',
  'ALU - Aludeckel Sparren',
  'ALU - Blende',
  'ALU - Blende_CP',
  'ALU - Dachrinne',
  'ALU - Dachrinne Kombi',
  'ALU - Dachrinne XL',
  'ALU - Dachrinne_CP',
  'ALU - Dachrinne_CP Deckel',
  'ALU - Deckel Fensterrahmen Profil',
  'ALU - Fensterrahmen Klickleiste',
  'ALU - Fensterrahmen L-Profil',
  'ALU - Fensterrahmen T-Profil',
  'ALU - Flache Führungsschiene unten - 3GL',
  'ALU - Flache Führungsschiene unten - 4GL',
  'ALU - Flache Führungsschiene unten - 5GL',
  'ALU - Führungschiene oben - 3GL',
  'ALU - Führungschiene oben - 4GL',
  'ALU - Führungschiene oben - 5GL',
  'ALU - Führungsprofil für Glasmodul',
  'ALU - Glaskoppelleiste oben',
  'ALU - Glaskoppelleiste unten',
  'ALU - L 120x20',
  'ALU - L 155x30',
  'ALU - L 52x20',
  'ALU - L-profil_CP (Oben)',
  'ALU - L-profil_CP (Unten)',
  'ALU - Panelprofil',
  'ALU - Panelprofil_SLIM',
  'ALU - Rechteckprofil 150 x 50',
  'ALU - Rechteckprofil 50 x 50',
  'ALU - Rechteckprofil 70 x 50',
  'ALU - Rechteckprofil 90 x 50',
  'ALU - Schwellenprofil',
  'ALU - Sparren',
  'ALU - Sparren 160 x 60',
  'ALU - Sparren 279 x 60',
  'ALU - Sparren mit LED Kanal',
  'ALU - Statikträger',
  'ALU - Statikträger-Deckel',
  'ALU - Stutze 110',
  'ALU - Stutze 160',
  'ALU - Stütze 160 x 160',
  'ALU - Wandanschlussprofil',
  'ALU - Wandprofil Kombi',
  'ALU - Wandprofil neu',
  'ALU - Wandprofil_CP',
  'ALU - Wetterschutzwinkel',
  'ALU-Abdichtungsprofil',
  'LAS -  Befestigung für Sparren 279 x 60',
  'LAS - CP_Glas-Stopper',
  'LAS - Dachrinne_CP - Deckel',
  'LAS - Deckel Führungschiene oben - 3GL',
  'LAS - Deckel Führungschiene oben - 4GL',
  'LAS - Deckel Führungschiene oben - 5GL',
  'LAS - Design Blende',
  'LAS - Fußverriegelung',
  'LAS - Führungsprofil Deckel',
  'LAS - Heizungslasche',
  'LAS - Schwerlastwinkel',
  'LAS - Seitendeckel Dachrinne Kombi',
  'LAS - Seitendeckel Dachrinne XL',
  'LAS - Seitendeckel Profil 110x110',
  'LAS - Seitendeckel Profil 110x160',
  'LAS - Seitendeckel Profil 50x50',
  'LAS - Seitendeckel Rinne',
  'LAS - Seitendeckel Rinne-Statikträger',
  'LAS - Seitendeckel Sparren',
  'LAS - Seitendeckel Statikträger',
  'LAS - Seitendeckel Wandprofil Kombi',
  'LAS - Seitendeckel Wandprofil neu',
  'LAS - Seitendeckel Wetterschutzwinkel',
  'LAS - Statikträger-Wandprofil Deckel',
  'LAS - Stop-Platte',
  'LAS - Wandprofil_CP - Deckel',
  'SCHL - Abdeckung Teil 1 (hinten)',
  'SCHL - Abdeckung Teil 2 (ohne Schloss)',
  'SCHL - Abdeckung Teil 2 (vorne)_L',
  'SCHL - Abdeckung Teil 2 (vorne)_P',
  'SCHL - Griff (mit Schloss)',
  'SCHL - Griff (ohne Schloss)',
  'SCHL - Standardgriff groß',
  'SCHL - Standardgriff klein'
];

const productIDs = [
  'ALU-5UFüH', 'ALU-4UFüH', 'ALU-3UFüH', 'ALU-FüGH', 'ALU-SCHWP',
  'ALU-5OFüH', 'ALU-4OFüH', 'ALU-3OFüH', 'ALU-SEIP', 'LAS-ABFüG',
  'LAS-ABFüS5', 'LAS-ABFüS4', 'LAS-ABFüS3', 'LAS-FUß', 'SCHL-GRSCH',
  'SCHL-GROSCH', 'SCHL-ABT2OS', 'SCHL-ABT1H', 'SCHL-ABT2VL', 'SCHL-ABT2VP',
  'SCHL-BGRI', 'SCHL-BGLM', 'ALU-RINN', 'ALU-STAT-DEC', 'ALU-WAN-N',
  'ALU-ABSCHL', 'ALU-SPAR-LED', 'ALU-FEN-L', 'ALU-FEN-T', 'ALU-FEN-KLI',
  'ALU-WAN-KOM', 'ALU-50x50', 'LAS-STAT', 'ALU-BLE', 'ALU-RINN-KOM',
  'ALU-WANDANSCHL', 'ALU-GLAKO-O', 'ALU-STAT', 'ALU-GLAKO-U', 'ALU-RINN-XL',
  'ALU-FEN-DEC', 'ALU-ABS-PAN', 'ALU-PANEL', 'ALU-PANEL-SLIM', 'ALU-150x50',
  'ALU-70x50', 'ALU-90x50', 'ALU-L120', 'ALU-L155', 'ALU-L52',
  'ALU-STU-110', 'ALU-STU-160', 'ALU-SPAR', 'ALU-DEC', 'LAS-RINN',
  'LAS-WETT', 'LAS-STU-WI', 'LAS-HEIZ', 'LAS-STU-50', 'LAS-ST-RN',
  'LAS-RN-XL', 'LAS-RN-KO', 'LAS-STU-110', 'LAS-STU-160', 'LAS-STOP-P',
  'LAS-SPAR-DEC', 'LAS-WAN-N', 'LAS-ST-WN', 'LAS-WN-KO', 'ALU-RINN-CP',
  'ALU-ABDKA', 'ALU-BLE-CP', 'ALU-ABDP', 'ALU-SPAR-160', 'ALU-SPAR-279',
  'ALU-STUCP-160', 'ALU-RINN-DEC-CP', 'ALU-LPRU-CP', 'ALU-LPRO-CP',
  'ALU-WANP-CP', 'LAS-RINN-DEC-CP', 'LAS-BSPAR-279', 'LAS-STOP-CP',
  'LAS-WANCP-DEC',
  'LAS-DES-BLE'
];

const predefinedColors = [
  "Anthrazit (Tiger 29/80077) DB 703 Eisenglimmerglau",
  "Anthrazit (Tiger 29/71289) RAL 7016",
  "Braun (Tiger 029/60740) Sepia Brown 'Marrone'",
  "Dunkelgrau (Tiger 029/50704) Fire Green - RAL 6009",
  "Anthrazit (Tiger 29/71289) RAL 7016 FS",
  "Graualuminium (Tiger 29/90147) RAL 9007",
  "Hellgrau (Tiger 029/90146) RAL 9006",
  "Reinweiß (Tiger 29/10797) RAL 9010",
  "Silber (Tiger 029/70786) Sparkling Iron Effect",
  "Verkehrsweiß Glatt (Tiger 29/10002) RAL 9016",
  "Verkehrsweiß strukturiert (Tiger 29/10246) RAL 9016"
];

// CONST - IDs HTML
const searchInput = document.getElementById("profile-search");
const resultsContainer = document.getElementById("profile-search-results");
const colorSelect = document.getElementById('color-select');
const colorCustomInput = document.getElementById('color-custom');
const addColorBtn = document.getElementById('add-color-btn');
